spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/**.xml
# 驼峰配置
  configuration:
    map-underscore-to-camel-case: true
# 打印sql
logging:
  level:
    com:
      zzf:
        demomybatis:
          mapper: debug


